### ISSUE TITLE
Help with how to use the developer usage

### ISSUE THREAD

**Issue by mktal04** [0mlml/chesshook-intermediary#3]
how do i communicate with the server? like use features such as whoareyou,sub,lock. In addition to that,how do i control the depth and strength of the engine? i am really sorry if i am asking a stupid question.i cant find any tutorial for this anywhere.

**Comment by mktal04** [comment]
do i have to install a text editor for that? because i cant type anything in cmd after i initiate .\main -engine ./<name of engine>

**Comment by 0mlml** [comment]
The developer usage section of the readme is for people that want to use the same server for some other software that would want to communicate with an engine running locally. The [userscript](https://github.com/0mlml/chesshook) already implements all of it. If you're writing some other software, you would connect using the websocket protocol. 

Controlling the skill level is as simple as passing a UCI argument to the server executable. For Stockfish, it would look like `.\main -engine .\stockfish_executable -uciargs "setoption name Skill Level value 3"`.
Controlling the depth of the engine involves disabling the "External Engine Auto Go Command" option and writing in your chosen 'go' command where you can change the depth of the engine. This is not really recommended unless you have a good reason for it as the "External Engine Auto Go Command" passes along the current clock state to the engine.
![image](https://github.com/0mlml/chesshook-intermediary/assets/63015852/b489a814-e58a-431d-b26a-916bfbd7e164)

**Comment by mktal04** [comment]
oh thank you so much.I just had a problem with stockfish taking alot of time. 32x bit operating systems arent the fastest and for some reason i cant get stockfish 16.1 to work since its not compatible with my machine. im stuck with stockfish 14 and below.

**Comment by mktal04** [comment]
best script ever!
